
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[264] =
    {   0,
        0,    0,   47,   46,   45,   45,   32,   46,   46,   32,
       32,   46,   32,   32,   32,   32,   46,   32,   36,   31,
       32,   32,   32,   41,   32,   32,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   33,   32,   34,    0,    0,   26,    0,
       42,    0,    0,    0,   35,   24,    0,    0,   29,   30,
        0,    0,    0,    0,   36,   28,   27,   28,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   15,   41,   41,
       41,   41,   41,   41,   41,   11,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   23,

        0,    0,   42,    0,    0,    0,   38,   38,    0,   25,
        0,    0,    0,    0,   43,    0,   37,   41,   41,   41,
       39,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   14,   41,   41,    6,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    0,    0,    0,   44,    0,    0,
       39,    4,   41,    9,    6,   41,   41,   41,   41,   13,
        8,   41,   41,   41,   17,   41,    5,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,    0,    0,    0,   19,    7,   41,   41,   41,

       41,   41,   41,    0,    0,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   20,   41,   41,   16,    0,    0,
       41,   41,   41,    0,    1,    0,   40,   41,   21,   22,
       12,   41,   41,   41,    0,    0,   41,   10,    0,   41,
       41,   41,    0,    0,   18,    0,    3,    0,    0,    0,
        3,    0,    0,    0,    0,    2,    0,    2,    0,    0,
        2,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   27,   27,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        1,    1,    1,    1,    6,    1,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[279] =
    {   0,
        0,    0,  479, 1358, 1358,   56,  451,   55,   27,  450,
       54,   99, 1358,  448,   50,   52,  452,   57,   52, 1358,
       42,  444,   55,   63,   66,   68,  140,  142,  146,  152,
      156,  173,  167,  185,  188,   70,  191,  204,  206,  208,
      222,  211,  224, 1358,  139, 1358,  163,  435, 1358,  173,
     1358,  245,  428,  415, 1358, 1358,  437,  431, 1358, 1358,
      422,  151,  170,  162,  240,  410, 1358,  407,  245,  248,
      251,  263,  266,  269,  281,  286,  299,  303,  315,  318,
      321,  336,  339,  352,  355,  359,  372,  375,  378,  392,
      395,  407,  410,  423,  426,  430,  443,  458,  462, 1358,

      377,  188,  208,  266,  372,  362, 1358, 1358,  374, 1358,
      236,  262,  274,  218, 1358,  232,  284,  465,  477,  484,
      489,  496,  501,  508,  513,  525,  528,  531,  545,  551,
      563,  566,  569,  584,  588,  591,  605,  609,  612,  624,
      630,  643,  647,  659,  662,  676,  680,  692,  696,  699,
      715,  718,  730,  737,  332,  325,  315, 1358,  281,  295,
      744,  750,  756,  762,  768,  774,  780,  786,  798,  802,
      805,  818,  822,  825,  838,  842,  856,  869,  862,  874,
      886,  889,  893,  906,  912,  925,  928,  941,  944,  947,
      959,  962,  304,  288,  276,  974,  977,  981,  993,  996,

      999, 1014, 1011,  317,  348, 1017, 1029, 1033, 1036, 1053,
     1065, 1068, 1072, 1084, 1088, 1102, 1105, 1108,  289,  285,
     1120, 1123, 1135,  295, 1358,  245, 1138, 1141, 1155, 1159,
     1171, 1174, 1177, 1189,  273,  217, 1196, 1208,  180, 1214,
     1220, 1226,  179,  338, 1238,  142,    0,  384,   66,   44,
        0,  333,  344,   68,  510, 1358,  348,  387,  407,  399,
      432,  680, 1358, 1268, 1271, 1278, 1282, 1289, 1296, 1299,
     1306, 1313, 1319, 1322, 1329, 1336, 1343, 1350
    } ;

static yyconst flex_int16_t yy_def[279] =
    {   0,
      263,    1,  263,  263,  263,  263,  263,  264,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  263,  263,  263,  263,  263,  263,  264,
      263,  266,  263,  263,  263,  263,  263,  267,  263,  263,
      263,  268,  269,  263,  263,  263,  263,  263,  265,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  263,

      263,  264,  264,  266,  263,  263,  263,  263,  267,  263,
      268,  271,  268,  269,  263,  272,  263,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  263,  263,  263,  263,  269,  272,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  263,  263,  263,  270,  270,  270,  270,  270,

      270,  270,  270,  263,  263,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  263,  263,
      270,  270,  270,  263,  263,  263,  270,  270,  270,  270,
      270,  270,  270,  270,  263,  263,  270,  270,  263,  270,
      270,  270,  273,  263,  270,  263,  274,  263,  275,  276,
      274,  275,  277,  276,  278,  263,  275,  275,  277,  276,
      276,  278,    0,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_uint16_t yy_nxt[1418] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   13,   14,   15,   13,   16,   17,   18,   19,   19,
       13,   20,   21,   22,   23,   13,   24,   25,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   24,   34,
       24,   35,   36,   24,   24,   37,   38,   39,   40,   41,
       42,   43,   24,   24,   24,   44,   45,   46,   13,   47,
       51,   53,   56,   59,   66,   67,   54,   59,   64,   62,
       65,   65,  255,   55,   63,   55,   60,   55,   67,   68,
       55,   69,   69,   52,   69,   69,   69,   69,   69,   69,
       71,   55,  256,   71,  253,   71,  255,   71,   48,   57,

       57,   89,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   57,   57,   57,   57,   69,   69,
       69,   69,   55,  112,   69,   69,   47,   71,  113,   71,
       69,   69,  115,   71,   69,   69,  224,   74,   51,   71,
      117,  117,  243,   71,   75,   69,   69,   77,   73,   72,
       76,   69,   69,   51,   71,  100,   78,   79,  116,   80,

       71,   52,   84,   69,   69,   48,   69,   69,   81,   69,
       69,   85,   71,   51,   82,   71,   52,   83,   71,  246,
      115,   86,   69,   69,   69,   69,   69,   69,   87,   69,
       69,   71,   88,   71,  115,   71,   52,   90,   71,   91,
       69,   69,   69,   69,   92,   93,  116,   50,  112,   71,
      103,   71,  244,  113,   94,   98,   64,   95,   65,   65,
      160,   96,   99,   69,   69,   97,  118,  118,   50,  118,
      122,  103,   71,  104,  112,  120,  243,  121,  120,  158,
      121,  118,  118,  115,  118,  118,  112,  118,  118,  239,
      120,  113,  121,  120,  104,  121,  120,  115,  121,  118,

      118,  124,  117,  117,  118,  118,  225,  204,  120,  116,
      121,  123,  126,  120,  205,  121,  125,  118,  118,  236,
      204,  118,  118,  160,  235,  220,  120,  205,  121,  127,
      120,  219,  121,  118,  118,  128,  118,  118,  256,  118,
      118,  248,  120,  249,  121,  120,  252,  121,  120,  258,
      121,  224,  129,  256,  118,  118,  195,  118,  118,  225,
      250,  253,  130,  120,  194,  121,  120,  131,  121,  132,
      118,  118,  259,  118,  118,  193,  253,  118,  118,  120,
      133,  121,  120,  107,  121,  134,  120,  248,  121,  249,
      118,  118,  256,  118,  118,  157,  118,  118,  226,  120,

      135,  121,  120,  136,  121,  120,  250,  121,  156,  252,
      118,  118,  258,  118,  118,  253,  155,  139,  138,  120,
      137,  121,  120,  256,  121,  118,  118,  255,  118,  118,
       55,  140,  141,   55,  120,  259,  121,  120,  110,  121,
      108,  118,  118,  142,  118,  118,  107,  144,  118,  118,
      120,  143,  121,  120,  146,  121,  256,  120,  106,  121,
      255,  118,  118,  105,  145,  148,  101,   49,   61,  147,
      120,   55,  121,   55,   49,  149,  118,  118,  263,  263,
      118,  118,  150,  118,  118,  120,  263,  121,  263,  120,
      151,  121,  120,  263,  121,  118,  118,  152,  263,  153,

      263,  154,  118,  122,  120,  263,  121,  118,  118,  263,
      263,  120,  254,  121,  161,  161,  120,  263,  121,  118,
      118,  263,  263,  120,  263,  121,  118,  118,  120,  263,
      121,  118,  118,  263,  261,  120,  263,  121,  262,  163,
      120,  263,  121,  118,  118,  162,  118,  118,  164,  118,
      118,  263,  120,  263,  121,  120,  263,  121,  120,  263,
      121,  263,  168,  118,  118,  263,  263,  263,  263,  118,
      118,  165,  120,  263,  121,  166,  167,  169,  120,  263,
      121,  118,  118,  263,  118,  118,  170,  118,  118,  263,
      120,  263,  121,  120,  263,  121,  120,  263,  121,  263,

      173,  172,  118,  118,  263,  171,  118,  118,   47,  118,
      118,  120,  263,  121,  263,  120,  263,  121,  120,  263,
      121,  174,  263,  118,  118,  263,  263,  118,  118,  263,
      118,  118,  120,  263,  121,  175,  120,  263,  121,  120,
      263,  121,  118,  118,  263,  263,  177,  176,  118,  118,
      263,  120,  263,  121,  263,  178,  263,  120,  263,  121,
      263,  118,  118,  263,  263,  118,  118,  179,  263,  180,
      120,  263,  121,  263,  120,  263,  121,  118,  118,  263,
      118,  118,  254,  263,  263,  263,  120,  263,  121,  120,
      263,  121,  181,  182,  118,  118,  263,  184,  118,  118,

      263,  263,  183,  120,  261,  121,  263,  120,  262,  121,
      118,  118,  263,  263,  118,  118,  263,  118,  118,  120,
      263,  121,  263,  120,  185,  121,  120,  263,  121,  186,
      263,  188,  263,  118,  118,  263,  118,  118,  263,  263,
      187,  263,  120,  189,  121,  120,  263,  121,  118,  118,
      263,  263,  137,  263,  190,  118,  118,  120,  263,  121,
      263,  191,  161,  161,  120,  263,  121,  263,  118,  118,
      263,  120,  263,  121,  118,  118,  263,  120,  192,  121,
      118,  118,  263,  120,  263,  121,  118,  118,  263,  120,
      263,  121,  118,  118,  263,  120,  196,  121,  118,  118,

      263,  120,  263,  121,  118,  118,  263,  120,  263,  121,
      263,  263,  263,  120,  263,  121,  118,  118,  263,  198,
      118,  118,  197,  118,  118,  120,  263,  121,  263,  120,
      263,  121,  120,  263,  121,  199,  118,  118,  263,  200,
      118,  118,  263,  118,  118,  120,  263,  121,  263,  120,
      263,  121,  120,  263,  121,  263,  118,  118,  263,  263,
      118,  118,  263,  202,  201,  120,  263,  121,  263,  120,
      165,  121,  204,  203,  118,  118,  263,  263,  263,  205,
      118,  118,  263,  120,  263,  121,  263,  118,  118,  120,
      263,  121,  118,  118,  263,  263,  120,  263,  121,  263,

      263,  120,  263,  121,  118,  118,  263,  118,  118,  263,
      206,  118,  118,  120,  263,  121,  120,  263,  121,  263,
      120,  207,  121,  263,  118,  118,  263,  263,  209,  263,
      118,  118,  208,  120,  263,  121,  263,  177,  263,  120,
      263,  121,  263,  118,  118,  263,  118,  118,  263,  263,
      210,  211,  120,  263,  121,  120,  263,  121,  212,  118,
      118,  213,  118,  118,  263,  118,  118,  263,  120,  263,
      121,  120,  263,  121,  120,  214,  121,  118,  118,  263,
      118,  118,  263,  263,  216,  263,  120,  215,  121,  120,
      263,  121,  118,  118,  263,  118,  118,  218,  263,  118,

      118,  120,  263,  121,  120,  263,  121,  217,  120,  263,
      121,  118,  118,  263,  118,  118,  263,  118,  118,  263,
      120,  263,  121,  120,  221,  121,  120,  263,  121,  118,
      118,  165,  118,  118,  222,  118,  118,  263,  120,  263,
      121,  120,  162,  121,  120,  223,  121,  118,  118,  263,
      139,  118,  118,  227,  118,  118,  120,  263,  121,  263,
      120,  263,  121,  120,  263,  121,  263,  263,  263,  263,
      177,  118,  118,  263,  263,  263,  229,  228,  263,  263,
      120,  263,  121,  118,  118,  263,  118,  118,  263,  230,
      118,  118,  120,  263,  121,  120,  263,  121,  162,  120,

      263,  121,  118,  118,  263,  263,  118,  118,  263,  263,
      231,  120,  263,  121,  263,  120,  215,  121,  263,  232,
      118,  118,  263,  118,  118,  263,  118,  118,  263,  120,
      263,  121,  120,  263,  121,  120,  263,  121,  118,  118,
      263,  118,  118,  263,  234,  233,  263,  120,  263,  121,
      120,  263,  121,  118,  118,  263,  118,  118,  263,  118,
      118,  263,  120,  263,  121,  120,  263,  121,  120,  237,
      121,  238,  263,  118,  118,  263,  240,  118,  118,  263,
      263,  227,  120,  263,  121,  263,  120,  263,  121,  118,
      118,  263,  118,  118,  263,  118,  118,  263,  120,  263,

      121,  120,  263,  121,  120,  263,  121,  118,  118,  263,
      162,  263,  241,  263,  118,  118,  120,  263,  121,  263,
      263,  263,  263,  120,  263,  121,  118,  118,  263,  263,
      242,  245,  118,  118,  263,  120,  263,  121,  118,  118,
      263,  120,  263,  121,  118,  118,  263,  120,  263,  121,
      263,  263,  263,  120,  177,  121,  118,  118,  263,  263,
      162,  197,  263,  263,  263,  120,  263,  121,   50,   50,
       50,   50,   50,   50,   50,   70,  263,   70,  102,  102,
      102,  102,  102,  102,  102,  109,  109,  263,  109,  111,
      111,  111,  111,  111,  111,  111,  114,  114,  114,  114,

      114,  114,  114,  119,  263,  119,  113,  113,  113,  113,
      113,  113,  113,  159,  159,  159,  159,  159,  159,  159,
      247,  263,  263,  263,  263,  247,  251,  263,  251,  252,
      252,  263,  252,  252,  252,  252,  254,  254,  254,  254,
      254,  263,  254,  257,  257,  257,  257,  257,  257,  257,
      260,  260,  260,  260,  260,  260,  260,    3,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_chk[1418] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    6,
        8,    9,   11,   15,   21,   21,    9,   16,   19,   18,
       19,   19,  250,   15,   18,   16,   16,   11,   23,   23,
       18,   24,   24,    8,   25,   25,   26,   26,   36,   36,
       24,   26,  254,   25,  249,   26,  254,   36,    6,   12,

       12,   36,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   27,   27,
       28,   28,   45,   62,   29,   29,   47,   27,   62,   28,
       30,   30,   63,   29,   31,   31,  246,   29,   50,   30,
       64,   64,  243,   31,   29,   33,   33,   30,   28,   27,
       29,   32,   32,  102,   33,   45,   30,   31,   63,   31,

       32,   50,   33,   34,   34,   47,   35,   35,   31,   37,
       37,   33,   34,  103,   32,   35,  102,   32,   37,  239,
      114,   34,   38,   38,   39,   39,   40,   40,   34,   42,
       42,   38,   35,   39,  116,   40,  103,   37,   42,   38,
       41,   41,   43,   43,   39,   39,  114,   52,  111,   41,
       52,   43,  236,  111,   39,   42,   65,   39,   65,   65,
      116,   40,   43,   69,   69,   41,   70,   70,  104,   71,
       71,  104,   69,   52,  112,   70,  235,   70,   71,  112,
       71,   72,   72,  159,   73,   73,  113,   74,   74,  226,
       72,  113,   72,   73,  104,   73,   74,  160,   74,   75,

       75,   73,  117,  117,   76,   76,  224,  193,   75,  159,
       75,   72,   75,   76,  193,   76,   74,   77,   77,  220,
      204,   78,   78,  160,  219,  195,   77,  204,   77,   76,
       78,  194,   78,   79,   79,   77,   80,   80,  252,   81,
       81,  244,   79,  244,   79,   80,  253,   80,   81,  253,
       81,  205,   78,  257,   82,   82,  157,   83,   83,  205,
      244,  252,   79,   82,  156,   82,   83,   80,   83,   81,
       84,   84,  253,   85,   85,  155,  257,   86,   86,   84,
       82,   84,   85,  109,   85,   83,   86,  248,   86,  248,
       87,   87,  258,   88,   88,  106,   89,   89,  205,   87,

       84,   87,   88,   85,   88,   89,  248,   89,  105,  259,
       90,   90,  259,   91,   91,  258,  101,   89,   88,   90,
       87,   90,   91,  260,   91,   92,   92,  260,   93,   93,
       68,   90,   91,   66,   92,  259,   92,   93,   61,   93,
       58,   94,   94,   91,   95,   95,   57,   93,   96,   96,
       94,   92,   94,   95,   94,   95,  261,   96,   54,   96,
      261,   97,   97,   53,   93,   95,   48,   22,   17,   94,
       97,   14,   97,   10,    7,   96,   98,   98,    3,    0,
       99,   99,   97,  118,  118,   98,    0,   98,    0,   99,
       97,   99,  118,    0,  118,  119,  119,   98,    0,   98,

        0,   99,  120,  120,  119,    0,  119,  121,  121,    0,
        0,  120,  255,  120,  122,  122,  121,    0,  121,  123,
      123,    0,    0,  122,    0,  122,  124,  124,  123,    0,
      123,  125,  125,    0,  255,  124,    0,  124,  255,  124,
      125,    0,  125,  126,  126,  123,  127,  127,  125,  128,
      128,    0,  126,    0,  126,  127,    0,  127,  128,    0,
      128,    0,  128,  129,  129,    0,    0,    0,    0,  130,
      130,  126,  129,    0,  129,  127,  127,  129,  130,    0,
      130,  131,  131,    0,  132,  132,  130,  133,  133,    0,
      131,    0,  131,  132,    0,  132,  133,    0,  133,    0,

      133,  132,  134,  134,    0,  131,  135,  135,  137,  136,
      136,  134,    0,  134,    0,  135,    0,  135,  136,    0,
      136,  135,    0,  137,  137,    0,    0,  138,  138,    0,
      139,  139,  137,    0,  137,  136,  138,    0,  138,  139,
        0,  139,  140,  140,    0,    0,  138,  137,  141,  141,
        0,  140,    0,  140,    0,  139,    0,  141,    0,  141,
        0,  142,  142,    0,    0,  143,  143,  140,    0,  141,
      142,    0,  142,    0,  143,    0,  143,  144,  144,    0,
      145,  145,  262,    0,    0,    0,  144,    0,  144,  145,
        0,  145,  142,  143,  146,  146,    0,  145,  147,  147,

        0,    0,  144,  146,  262,  146,    0,  147,  262,  147,
      148,  148,    0,    0,  149,  149,    0,  150,  150,  148,
        0,  148,    0,  149,  146,  149,  150,    0,  150,  147,
        0,  149,    0,  151,  151,    0,  152,  152,    0,    0,
      148,    0,  151,  150,  151,  152,    0,  152,  153,  153,
        0,    0,  152,    0,  151,  154,  154,  153,    0,  153,
        0,  153,  161,  161,  154,    0,  154,    0,  162,  162,
        0,  161,    0,  161,  163,  163,    0,  162,  154,  162,
      164,  164,    0,  163,    0,  163,  165,  165,    0,  164,
        0,  164,  166,  166,    0,  165,  163,  165,  167,  167,

        0,  166,    0,  166,  168,  168,    0,  167,    0,  167,
        0,    0,    0,  168,    0,  168,  169,  169,    0,  167,
      170,  170,  166,  171,  171,  169,    0,  169,    0,  170,
        0,  170,  171,    0,  171,  168,  172,  172,    0,  169,
      173,  173,    0,  174,  174,  172,    0,  172,    0,  173,
        0,  173,  174,    0,  174,    0,  175,  175,    0,    0,
      176,  176,    0,  174,  172,  175,    0,  175,    0,  176,
      173,  176,  178,  176,  177,  177,    0,    0,    0,  178,
      179,  179,    0,  177,    0,  177,    0,  178,  178,  179,
        0,  179,  180,  180,    0,    0,  178,    0,  178,    0,

        0,  180,    0,  180,  181,  181,    0,  182,  182,    0,
      179,  183,  183,  181,    0,  181,  182,    0,  182,    0,
      183,  180,  183,    0,  184,  184,    0,    0,  183,    0,
      185,  185,  181,  184,    0,  184,    0,  182,    0,  185,
        0,  185,    0,  186,  186,    0,  187,  187,    0,    0,
      184,  185,  186,    0,  186,  187,    0,  187,  186,  188,
      188,  187,  189,  189,    0,  190,  190,    0,  188,    0,
      188,  189,    0,  189,  190,  188,  190,  191,  191,    0,
      192,  192,    0,    0,  190,    0,  191,  189,  191,  192,
        0,  192,  196,  196,    0,  197,  197,  192,    0,  198,

      198,  196,    0,  196,  197,    0,  197,  191,  198,    0,
      198,  199,  199,    0,  200,  200,    0,  201,  201,    0,
      199,    0,  199,  200,  198,  200,  201,    0,  201,  203,
      203,  200,  202,  202,  199,  206,  206,    0,  203,    0,
      203,  202,  201,  202,  206,  202,  206,  207,  207,    0,
      203,  208,  208,  206,  209,  209,  207,    0,  207,    0,
      208,    0,  208,  209,    0,  209,    0,    0,    0,    0,
      209,  210,  210,    0,    0,    0,  208,  207,    0,    0,
      210,    0,  210,  211,  211,    0,  212,  212,    0,  210,
      213,  213,  211,    0,  211,  212,    0,  212,  211,  213,

        0,  213,  214,  214,    0,    0,  215,  215,    0,    0,
      213,  214,    0,  214,    0,  215,  212,  215,    0,  214,
      216,  216,    0,  217,  217,    0,  218,  218,    0,  216,
        0,  216,  217,    0,  217,  218,    0,  218,  221,  221,
        0,  222,  222,    0,  217,  216,    0,  221,    0,  221,
      222,    0,  222,  223,  223,    0,  227,  227,    0,  228,
      228,    0,  223,    0,  223,  227,    0,  227,  228,  221,
      228,  222,    0,  229,  229,    0,  228,  230,  230,    0,
        0,  223,  229,    0,  229,    0,  230,    0,  230,  231,
      231,    0,  232,  232,    0,  233,  233,    0,  231,    0,

      231,  232,    0,  232,  233,    0,  233,  234,  234,    0,
      232,    0,  233,    0,  237,  237,  234,    0,  234,    0,
        0,    0,    0,  237,    0,  237,  238,  238,    0,    0,
      234,  237,  240,  240,    0,  238,    0,  238,  241,  241,
        0,  240,    0,  240,  242,  242,    0,  241,    0,  241,
        0,    0,    0,  242,  241,  242,  245,  245,    0,    0,
      240,  242,    0,    0,    0,  245,    0,  245,  264,  264,
      264,  264,  264,  264,  264,  265,    0,  265,  266,  266,
      266,  266,  266,  266,  266,  267,  267,    0,  267,  268,
      268,  268,  268,  268,  268,  268,  269,  269,  269,  269,

      269,  269,  269,  270,    0,  270,  271,  271,  271,  271,
      271,  271,  271,  272,  272,  272,  272,  272,  272,  272,
      273,    0,    0,    0,    0,  273,  274,    0,  274,  275,
      275,    0,  275,  275,  275,  275,  276,  276,  276,  276,
      276,    0,  276,  277,  277,  277,  277,  277,  277,  277,
      278,  278,  278,  278,  278,  278,  278,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[47] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "project.l"
#line 4 "project.l"
	#include<stdio.h>
	# include <math.h>
	#include"y.tab.h"
	#include<math.h>
	#include "help.h"
	
#line 899 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 18 "project.l"


#line 1120 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1358 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "project.l"
{the_medium_to_display(yytext,36, yylineno); return id; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "project.l"
{ the_medium_to_display(yytext, 1, yylineno);return HEADER;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "project.l"
{the_medium_to_display(yytext, 2, yylineno); return DEFINE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "project.l"
{ the_medium_to_display(yytext, 3, yylineno); return storage_const;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "project.l"
{ the_medium_to_display(yytext, 4, yylineno); return type_const;}	
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "project.l"
{ int noT = the_medium_to_display(yytext, 4, yylineno); return type_const;}	
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "project.l"
{ the_medium_to_display(yytext, 5, yylineno); return qual_const;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "project.l"
{the_medium_to_display(yytext, 6, yylineno); return enum_const; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "project.l"
{ the_medium_to_display(yytext, 7, yylineno); return CASE;}	
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "project.l"
{ the_medium_to_display(yytext, 8, yylineno); return DEFAULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "project.l"
{ the_medium_to_display(yytext, 9, yylineno); return IF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "project.l"
{the_medium_to_display(yytext, 10, yylineno); return SWITCH; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "project.l"
{ the_medium_to_display(yytext, 11, yylineno);return ELSE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "project.l"
{ the_medium_to_display(yytext, 12, yylineno); return FOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "project.l"
{ the_medium_to_display(yytext, 13, yylineno); return DO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "project.l"
{ the_medium_to_display(yytext, 14, yylineno); return WHILE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "project.l"
{ the_medium_to_display(yytext, 15, yylineno); return GOTO;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "project.l"
{the_medium_to_display(yytext, 16, yylineno); return CONTINUE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "project.l"
{ the_medium_to_display(yytext, 17, yylineno); return BREAK;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "project.l"
{ the_medium_to_display(yytext, 18, yylineno); return struct_const;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "project.l"
{the_medium_to_display(yytext, 19, yylineno); return RETURN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "project.l"
{ the_medium_to_display(yytext, 20, yylineno); return SIZEOF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "project.l"
{the_medium_to_display(yytext, 21, yylineno); return or_const; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "project.l"
{the_medium_to_display(yytext, 22, yylineno); return and_const; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "project.l"
{ the_medium_to_display(yytext, 23, yylineno); return param_const;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "project.l"
{ the_medium_to_display(yytext, 24, yylineno); return eq_const;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "project.l"
{the_medium_to_display(yytext, 25, yylineno); return rel_const; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "project.l"
{ the_medium_to_display(yytext, 26, yylineno); return shift_const;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "project.l"
{ the_medium_to_display(yytext, 27, yylineno); return inc_const;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "project.l"
{the_medium_to_display(yytext, 28, yylineno); return point_const; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "project.l"
{ the_medium_to_display(yytext, 29, yylineno);set = set + 1; return yytext[0];}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "project.l"
{ the_medium_to_display(yytext, 29, yylineno); return yytext[0];}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "project.l"
{ letsPush(); the_medium_to_display(yytext, 29, yylineno); return yytext[0];}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "project.l"
{ letsPop(); the_medium_to_display(yytext, 29, yylineno); return yytext[0];}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "project.l"
{the_medium_to_display(yytext, 30, yylineno); return PUNC; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "project.l"
{ the_medium_to_display(yytext, 31, yylineno); return int_const;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "project.l"
{the_medium_to_display(yytext, 32, yylineno); return float_const; }	
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "project.l"
{ the_medium_to_display(yytext, 33, yylineno);  return char_const ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "project.l"
{ int noT = the_medium_to_display(yytext, 37, yylineno); if(noT== 1){ return int_id; } else if(noT==2) {return float_id;} else if(noT==3){return char_id;} else {return id;} }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "project.l"
{ the_medium_to_display(yytext, 38, yylineno); return id;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "project.l"
{  int noT = the_medium_to_display(yytext, 34, yylineno); if(noT== 1){ return int_id; } else if(noT==2) {return float_id;} else if(noT==3){ return char_id;} else {return id;} }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 103 "project.l"
{ the_medium_to_display(yytext, 35, yylineno);  return string;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 105 "project.l"
;
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 106 "project.l"
;
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 107 "project.l"
;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 109 "project.l"
ECHO;
	YY_BREAK
#line 1422 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 109 "project.l"



int yywrap(void)
{
    return 1;
}




